alias :e='vim'
alias oldvim='/usr/bin/vim'
alias ev='$EDITOR ~/.vimrc'
alias ez='$EDITOR ~/.zshrc && source ~/.zshrc'
alias ealias='$EDITOR ~/.config/zsh/aliases.zsh && source ~/.config/zsh/aliases.zsh'
alias sy='systemctl'
alias ls='/usr/local/bin/gls --color=auto'
alias ll='/usr/local/bin/gls --color=auto -GFhl'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias git='LANG=en_US.UTF-8 git'
alias g="git status"
alias be='bundle exec'
